name: ci-docker

on:
  release:
    types: [published]
  workflow_dispatch: {}
  push:
    branches:
      - "dev-docker"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push to Docker Hub with version tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_default
          push: true
          tags: hexxa/quickshare:${{ env.RELEASE_VERSION }}
      - name: Build and push to Docker Hub with latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_default
          push: true
          tags: hexxa/quickshare:latest
