name: ci-docker-test

on:
  # release:
  #   types: [published]
  # workflow_dispatch: {}
  push:
    branches:
      - "dev-docker"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ihexxa
          password: ${{ secrets.GHCR_PWD }}
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push to Docker Hub with version tag
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile_default
          push: true
          tags: ghcr.io/ihexxa/quickshare:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push to Docker Hub with version tag
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile_default
          push: true
          tags: ghcr.io/ihexxa/quickshare:latest
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ghcr.io/ihexxa/quickshare:${{ env.RELEASE_VERSION }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
