name: ci-binary

# Controls when the action will run.
on:
  release:
    types: [published]
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2 # Install runtimes
        with:
          go-version: "^1.15.0"
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: go version
      - name: Install dependencies
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Upload artifacts
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*"
          tags: true
          draft: false
          overwrite: true
